# Generated by Django 5.2 on 2025-04-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("lokasi", models.CharField(max_length=255)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="laporan_pics/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("menunggu", "Menunggu"),
                            ("diproses", "Diproses"),
                            ("selesai", "Selesai"),
                        ],
                        default="menunggu",
                        max_length=10,
                    ),
                ),
                ("tanggal_laporan", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
